version: '3.8'

services:
  postgres:
    image: postgres:17 # PostgreSQL 17 버전 이미지를 사용합니다.
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: develop # 원하는 사용자 이름으로 변경하세요.
      POSTGRES_PASSWORD: developer12!@ # 강력한 비밀번호로 변경하세요.
      POSTGRES_DB: user # 사용할 데이터베이스 이름으로 변경하세요.
    ports:
      - "5433:5432" # 호스트의 5432 포트를 컨테이너의 5432 포트로 매핑합니다.
    volumes:
      - postgres_data:/var/lib/postgresql/data # 데이터 영속성을 위해 볼륨을 사용합니다.

  redis:
    image: redis:latest # 최신 Redis 이미지를 사용합니다. (예: redis:7.2) 특정 버전을 원하시면 redis:7.2 와 같이 명시할 수 있습니다.
    container_name: my_redis_cache
    restart: always
    ports:
      - "6379:6379" # 호스트의 6379 포트를 컨테이너의 6379 포트로 매핑합니다.
    volumes:
      - redis_data:/data # 데이터 영속성을 위해 볼륨을 사용합니다.
    command: redis-server --save 60 1 --loglevel warning # 60초마다 변경 사항이 1개 이상 있을 경우 디스크에 저장합니다.
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data: # PostgreSQL 데이터를 저장할 명명된 볼륨입니다.
    driver: local
  redis_data: # Redis 데이터를 저장할 명명된 볼륨입니다.
    driver: local